# -*- coding: utf-8 -*-
"""task1_ml_linear_regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lULD-yncT04GiorLct7Vl4zdXlYpdp1l

# Task 1 - Linear Regression Model (California Housing Dataset)

## Objective
Build and evaluate a Linear Regression model using the California Housing dataset.

### Workflow
1. Load Dataset
2. Explore Dataset (EDA)
3. Preprocess Data
4. Train/Test Split
5. Train Linear Regression Model
6. Evaluate Model
7. Save Model
"""

# Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import joblib

"""## Load Dataset"""

housing = fetch_california_housing(as_frame=True)

df = housing.frame

# Display first 5 rows
df.head()

"""## Dataset Information"""

df.info()

"""## Statistical Summary"""

df.describe()

"""## Correlation Heatmap"""

corr = df.corr(numeric_only=True)

plt.figure(figsize=(10,6))
plt.imshow(corr, cmap='viridis', aspect='auto')
plt.xticks(range(len(corr.columns)), corr.columns, rotation=90)
plt.yticks(range(len(corr.columns)), corr.columns)
plt.colorbar()
plt.title("Correlation Heatmap")
plt.show()

"""## Split Features and Target"""

X = df.drop("MedHouseVal", axis=1)
y = df["MedHouseVal"]

"""## Train-Test Split"""

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

"""## Train Linear Regression Model"""

model = LinearRegression()

model.fit(X_train, y_train)

"""## Predictions"""

y_pred = model.predict(X_test)

"""## Evaluate Model"""

mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print("MAE:", mae)
print("RMSE:", rmse)
print("R2 Score:", r2)

"""## Actual vs Predicted Plot"""

plt.figure(figsize=(6,4))
plt.scatter(y_test, y_pred, alpha=0.5)
plt.xlabel("Actual Prices")
plt.ylabel("Predicted Prices")
plt.title("Actual vs Predicted House Prices")
plt.show()

"""## Save Model"""

joblib.dump(model, "california_housing_model.pkl")

print("Model saved successfully!")

"""# Conclusion

The Linear Regression model was trained successfully using the California Housing dataset.

### Future Improvements
- Feature Engineering
- Hyperparameter Tuning
- Advanced Regression Models

"""